name: POI-Tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "apis/poi/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: "apis/poi"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      #./apis/poi/web/poi.csproj
      
    - name: Build
      run: dotnet build
      #--no-restore ./apis/poi/web/poi.csproj --configuration Release
      
    - name: Unit Test
      #run: dotnet test ./apis/poi/web/poi.csproj --filter "FullyQualifiedName~UnitTest" --logger "trx;LogFileName=UnitTestResults.trx" --results-directory ./apis/poi/web/TestResults
      run: dotnet test --filter "FullyQualifiedName~UnitTest" --logger "trx;LogFileName=UnitTestResults.trx" --results-directory ./TestResults
      
    - name: Publish Test Reports
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: TestResults
        path: ./apis/poi/TestResults/UnitTestResults.trx
        reporter: dotnet-trx
        fail-on-error: false

    - name: Create issue on failure
      if: (failure() && github.event_name != 'pull_request')
      run: |
        body='
          ### Unit Test `failure`
          <details>
          <summary>Workflow details</summary>
          Workflow name: `${{ github.workflow }}`
          Action: `${{ github.event_name }}`
          Job: `${{ github.job }}`
          PR: #${{ github.event.number }}
          </details>
          Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Pusher: @${{ github.actor }}'
        title='Unit Tests Failed'
        gh issue create --title "${title}" --body "${body}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create PR Comment 
      if: (failure() && github.event_name == 'pull_request') || success()
      run: |
        body='
          ### Unit Test `failure`
          <details>
          <summary>Workflow details</summary>
          Workflow name: `${{ github.workflow }}`
          Action: `${{ github.event_name }}`
          Job: `${{ github.job }}`
          PR: #${{ github.event.number }}
          </details>
          Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Pusher: @${{ github.actor }}'
        title='Unit Tests Failed'
        gh pr comment ${{ github.event.number }} ##--body "${body}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
